vich_uploader:
  db_driver: orm

  mappings:
    Produits:
      uri_prefix: /images/produits
      upload_destination: "%kernel.project_dir%/public/assets/images/produits"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    Services:
      uri_prefix: /images/services
      upload_destination: "%kernel.project_dir%/public/assets/images/services"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    Reparations:
      uri_prefix: /images/reparations
      upload_destination: "%kernel.project_dir%/public/assets/images/reparations"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    Actualiter:
      uri_prefix: /images/actualiter
      upload_destination: "%kernel.project_dir%/public/assets/images/actualiter"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    Logos:
      uri_prefix: /images/logos
      upload_destination: "%kernel.project_dir%/public/assets/images/logos"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
